Added support for angular and linear velocity
immersive-web/webxr pull request #1182
Opened 2021-03-12 18:48 UTC by cabanier

Closes #619

Also silences a couple of bikeshed warnings.

2021-03-12 18:49 UTC, cabanier commented
@Manishearth why can I not add reviewers?

2021-03-13 00:46 UTC, toji requested changes
LGTM after one correction.

2021-03-13 00:46 UTC, toji commented on index.bs
> +The <dfn attribute for="XRPose">angularVelocity</dfn> attribute describes the angular velocity in meters per second relative to the base {{XRSpace}}. If the user agent can't populate this, it's allow
Angular velocity isn't measured in meters per second. It seems like OpenXR reports this in radians per second, which seems fairly sensible.

2021-03-13 00:46 UTC, toji commented
GitHub had a hangover this morning, which is why you couldn't add reviewers. I think it's generally better now.

2021-03-13 04:42 UTC, cabanier commented
> GitHub had a hangover this morning, which is why you couldn't add reviewers. I think it's generally better now.

I still can't add reviewers.

2021-03-13 04:46 UTC, cabanier commented
I was looking into a possible implementation and there are some spaces where velocity will never be reported.
For instance XRJointSpaces and XRTargetRaySpace with a XRTargetRayMode different than POINTING.

Should we add those exceptions to the spec, or leave it up to the UA?

2021-03-13 17:44 UTC, toji commented
I think it's best to leave that up to the UA. For example, I can see that OpenXR has an extension for [hand joint velocity](https://www.khronos.org/registry/OpenXR/specs/1.0/man/html/openxr.html#_xrhandjointvelocityext3) and I suspect that the tracking method (ie: optical vs sensors) will make a big difference in what velocities are available. I wouldn't want to prematurely prevent future advances in tracking.

If we're concerned about developers needing to know what spaces can and can't report velocities, it would probably be best to report that as a property of the space (`hasLinearVelocity`/`hasAngularVelocity` booleans, maybe?) but I don't know that we can do that consistently and reliably on all platforms, and I believe even spaces that CAN report velocities may have moments where it lapses, such after the first frame or two of tracking (depending on the tracking method). As a result, developers will need to be able to handle `null` velocities no matter what.

We should probably just leave it as "If the user agent can't populate this, it's allowed to return `null`."

2021-03-13 17:45 UTC, toji approved these changes
Thanks for fixing the angular velocity definition, by the way!

2021-03-14 01:06 UTC, cabanier commented
@toji thanks for approving! Can you merge it for me? I'm not able to.

2021-03-14 01:09 UTC, toji commented
If you don't mind I'd like to make sure that @Manishearth has had a chance to look before I do? That should be Tues at the latest, since we have our editors sync then. Normally I wouldn't be too concerned but given this is a change to a largely "shipped" spec I feel a smidge of extra caution is warranted.

I doubt there's going to be any concerns, though.

2021-03-14 01:10 UTC, cabanier commented
I see. That sounds good! There's no hurry to get it in.

2021-03-14 06:09 UTC, Manishearth approved these changes
Seems good now.

One note: angular velocity can be obtained from the other attributes; and we tend towards not having APIs that expose information that can be calculated by the author, but I think it's fine in this case.

2021-03-14 06:09 UTC, merged